name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - name: Permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build -PGITHUB_USER=${{ secrets._GITHUB_USER }} -PGITHUB_TOKEN=${{ secrets._GITHUB_TOKEN }}
